config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions"}


  root to: "pages#index"

  resources :creatures
  resources :locations
  resources :maps
  resources :user_creatures
  resources :creature_locations
  resources :user_locations


  get 'game_master/catch' => 'game_master#catch', as: :game_master_catch 
end

app/models/creature.rb
class Creature < ActiveRecord::Base
	belongs_to :user

	validates :name, uniqueness: true

	CREATURETYPES = ["fire", "water", "grass"]
end

app/models/creature_location.rb
class CreatureLocation < ActiveRecord::Base
	belongs_to :location
	belongs_to :creature
end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :creature_locations
	has_many :user_locations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :user_locations
	#accepts_nested_form_for :user_locations

end

app/models/user_location.rb
class UserLocation < ActiveRecord::Base
	belongs_to :location
	belongs_to :user
end

app/models/usercreature.rb
class Usercreature < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  maps_path
  end
end

app/controllers/creature_locations_controller.rb
class CreatureLocationsController < ApplicationController

  def index
    @creature_locations = CreatureLocation.all
    render :template => "creature_locations/index"
  end

  def new
    @creature_location = CreatureLocation.new
    render :template => "creature_locations/new"
  end

  def create
    @creature_location = CreatureLocation.new(creature_location_params)

    if @creature_location.save
      redirect_to creature_locations_path
    else
      render :template => "creature_locations/new"
    end
  end

  def destroy
    CreatureLocation.find(params[:id]).destroy!
    redirect_to creature_locations_path
  end
  
  def creature_location_params
    params.require(:creature_location).permit!
  end

end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
    render :template => "creatures/index"
  end

  def new
    @creature = Creature.new
    render :template => "creatures/new"
  end

  def create
    @creature = Creature.new(creature_params)

    if @creature.save
      redirect_to creatures_path
    else
      render :template => "creatures/new"
    end
  end

  def destroy
    Creature.find(params[:id]).destroy!
    redirect_to creatures_path
  end
  
  def creature_params
    params.require(:creature).permit!
  end

end

app/controllers/game_master_controller.rb
class GameMasterController < ApplicationController
	def index
	end

	def trade
		@user = User.find(params[:id])
	end


	def battle
		
	end

	def catch


		render :template => "game_master/catch"

		#render json: @creaturesko
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
    render :template => "locations/index"
  end

  def new
    @location = Location.new
    render :template => "locations/new"
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to locations_path
    else
      render :template => "locations/new"
    end
  end

  def destroy
    Location.find(params[:id]).destroy!
    redirect_to locations_path
  end
  
  def location_params
    params.require(:location).permit!
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def index
		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
end 

app/controllers/user_creatures_controller.rb
class UserCreaturesController < ApplicationController
	def new 
		@creatureko = UserCreature.new
		render :template => "usercreatures/new"
	end

	def create
		@creatureko = UserCreature.new(usercreature_params)

		if @creatureko.save
		  redirect_to root_path
		else
		  render :template => "usercreatures/new"
	end

	def usercreature_params
    	params.require(:location).permit!
 	end
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
	def index
    @user_locations = UserLocation.all
    render :template => "user_locations/index"
  end

  def new
    @user_location = UserLocation.new
    render :template => "user_locations/new"
  end

  def create
    @user_location = UserLocation.new(user_location_params)

    if @user_location.save
      redirect_to user_locations_path
    else
      render :template => "user_locations/new"
    end
  end

  def destroy
    UserLocation.find(params[:id]).destroy!
    redirect_to user_locations_path
  end
  
  def user_location_params
    params.require(:user_location).permit!
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creature_locations_helper.rb
module CreatureLocationsHelper
end

app/helpers/game_master_helper.rb
module GameMasterHelper
end

app/helpers/user_creatures_helper.rb
module UserCreaturesHelper
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/views/creatures/index.html.erb
<h2>Creatures</h2>
<%= link_to "Create Creature", new_creature_path %>
<%= link_to "Go back to home", maps_path %>
<hr>

  <table width="100%">
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Options</th>
    </tr>
    <tr>
        <% Creature::CREATURETYPES.each do |creature_type| %>
          <% Creature.all.where(:creature_type => creature_type).each do |creature| %>
        <td align="center"><%= creature.name %></td>
        <td align="center"> <%= creature.creature_type %></td>
        <td align="center"><%= link_to "Destroy", creature_path(creature.id), :method => :delete, :data => { :confirm => "Are you sure you?" } %> 
    </tr>
        <% end %>
      <% end %>
  </table>

app/views/creatures/new.html.erb
<h1>New Creature</h1>

<%= simple_form_for(@creature) do |f| %>
  <%= f.input :name %>
  <%= f.input :creature_type, :as => :select, :collection => Creature::CREATURETYPES %>
    <hr>
  <%= f.submit "Create Creature" %>
<% end %>

<%= link_to "Back to creatures", creatures_path %>

app/views/game_master/walk.html.erb
<h1>Choose a location</h1>

<%= simple_form_for(@movement) do |f| %>

  <%= f.association :location %>
  <%= f.input :name %>
    <hr>
  <%= f.submit "Create Location" %>
<% end %>

<%= link_to "Back to locations", locations_path %>

app/views/locations/index.html.erb
<h2>Locations</h2>
<%= link_to "Create Location", new_location_path %>
<%= link_to "Go back to home", maps_path %>
<hr>

  <table width="100%">
    <tr>
      <th>Name</th>
      <th>X-coordinate</th>
      <th>Y-coordinate</th>
      <th>Options</th>
    </tr>
    <tr>
      <% @locations.each do |location| %>
      <td align="center"><%= location.name %></td>
      <td align="center"> <%= location.xcoor%></td>
      <td align="center"> <%= location.ycoor %></td>
      <td align="center"><%= link_to "Destroy", location_path(location.id), :method => :delete, :data => { :confirm => "Are you sure you?" } %> </td>
    </tr>
      <% end %>
  </table>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= simple_form_for(@location) do |f| %>
  <%= f.input :name %>
  <%= f.input :xcoor %>
  <%= f.input :ycoor %>
    <hr>
  <%= f.submit "Create Location" %>
<% end %>

<%= link_to "Back to locations", locations_path %>